### ISSUE TITLE
Not working with jbarlow83/ocrmypdf:latest (v9.0.3)

### ISSUE THREAD

**Issue by princemaxwell** [stweiss/FileBasedMiniDMS#11]
Hello,
the script isn't running with version 9.0.3 of ocrmypdf.

`2019-09-26 23:20:02 Scanning for new scans: /volume1/scan/_inbox
2019-09-26 23:20:02 Run Docker: docker run --name ocr --rm -u 1024 -v "/volume1/scan/_inbox:/home/docker" jbarlow83/ocrmypdf -sr -l deu "20190926224544.pdf" "OCR_20190926224544.pdf" 2>&1
2019-09-26 23:20:12 Docker output:
   ERROR - OutputFileAccessError: Output file location (OCR_20190926224544.pdf) is not a writable file.
2019-09-26 23:20:12 run: pdftotext -l 1 "/volume1/scan/_inbox/OCR_20190926224544.pdf" - 2>&1
2019-09-26 23:20:12 pdftotext output:
 I/O Error: Couldn't open file '/volume1/scan/_inbox/OCR_20190926224544.pdf': No such file or directory.`

**Comment by Chris122AT** [comment]
I have the same problem!

If I use --mask-barcodes, there comes the following error:
`ocrmypdf: error: unrecognized arguments: --mask-barcodes`

If the script starts without handing over --mask-barcodes, the result is the same as princemaxwell has posted.

The script is running on a Synology NAS (cron job) as **root**!

**Comment by geimist** [comment]
> If I use --mask-barcodes, there comes the following error:   

See you [here (changelog of v9.0.0)](https://ocrmypdf.readthedocs.io/en/latest/release_notes.html#v9-0-0):

> The --mask-barcodes experimental feature has been dropped due to poor reliability and occasional crashes, both due to the underlying library that implements this feature (Leptonica).

**Comment by Chris122AT** [comment]
Thanks! I did not read the last changelogs.

**Comment by stweiss** [comment]
Thanks for reporting this @princemaxwell!
This issue exists since ocrmypdf v9.0.0.
As a quick workaround you can specify a working version in the config.php:
`$dockercontainer = "jbarlow83/ocrmypdf:v8.3.2";`

I'm looking into this to find a solution.

**Comment by stweiss** [comment]
Please verify with the new version, @princemaxwell

**Comment by princemaxwell** [comment]
OCR works, but what about $archivefolder?
I can't remember exactly, but the OCR'd scans were put into $archivefolder in 0.14 (with ocrmypdf 8.3.2)?!?

With 0.15 the original scans are overwritten with the OCR'd scan in "_inbox".

So now i have the problem that my PDFs will be OCR'd everytime again and again.
I have to use
`$matchWithoutOCR = "*";`
because my scan have the syntax "20190928105010.pdf".

After OCR it is called "OCR_20190928105010.pdf".

And after renaming it is called "2019-09-28 Stadtwerke #tag.pdf".

Because of having it in "_inbox" anymore, it will be OCR'd as long as i let it in this folder.

**Comment by Guacam-Ole** [comment]
At least in my configuration the.OCRred version always has been stored in the same folder with the "ocr"-prefix.
So this is nothing that changed through an update.

Btw:.would be more useful to create a new issue than to add this to a closed issue with another Topic.
