### ISSUE TITLE
Invalide Reference Format

### ISSUE THREAD

**Issue by mullischlumpf** [stweiss/FileBasedMiniDMS#14]
Hallo,

Ich bekomme leider bei jeder PDF Datei den folgenden Fehler:

2019-12-01 15:39:39 Scanning for new scans: /volume1/documents/scans
2019-12-01 15:39:39 Run Docker: docker run —name ocr —rm -i jbarlow83/ocrmypdf -sr -l deu+eng - - <"/volume1/documents/scans/113922scan.pdf" 2>&1 >"/volume1/documents/scans/OCR113922scan.pdf"
2019-12-01 15:39:39 Docker output:
 docker: invalid reference format. 
See 'docker run --help'.

Ich habe schon verschiedene ocrmypdf Versionen versucht leider ohne Erfolg. Die Dateien sind ganz normale PDF Dateien.

**Comment by stweiss** [comment]
Hallo @mullischlumpf,

der Fehler deutet darauf hin, dass etwas mit dem "docker run" Kommando nicht stimmt.
Eigentlich sollten da zwei Bindestriche bei ...`--name ocr --rm`... sein. In deinem Text ist da jeweils nur ein langer Strich. Das könnte zu dem Fehler führen.
Allerdings ist der Code dazu in FileBasedMiniDMS.php, hast du dort was geändert?

Gruß
Stefan

**Comment by mullischlumpf** [comment]
Hallo Stefan,

oh je du hast recht :-/ 
Da hat es beim hin- und her kopieren wohl die Datei kaputt gemacht. Ich habe sie nochmal neu runtergeladen und nun funktioniert es wieder.

Viele Dank für den Hinweis und auch deine Arbeit die du hier investierst 👍 👍 👍 

Gruß
Marcel

**Comment by stweiss** [comment]
Danke für die Rückmeldung.
Solange sich der Aufwand in Grenzen hält mach ich das gern. Dient ja auch dem Selbstzweck :)

Grüße
Stefan
