### ISSUE TITLE
PHP Errors

### ISSUE THREAD

**Issue by denizkoekden** [stweiss/FileBasedMiniDMS#6]
Hello,
I have the following problem:

When running the Script via php I get the following error:

"PHP Notice:  Undefined variable: logfile in /srv/ocr/FileBasedMiniDMS/FileBasedMiniDMS.php on line 51
PHP Notice:  Undefined variable: timezone in /srv/ocr/FileBasedMiniDMS/FileBasedMiniDMS.php on line 53
PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /srv/ocr/FileBasedMiniDMS/FileBasedMiniDMS.php:53
Stack trace:
#0 /srv/ocr/FileBasedMiniDMS/FileBasedMiniDMS.php(53): DateTimeZone->__construct('')
#1 {main}
  thrown in /srv/ocr/FileBasedMiniDMS/FileBasedMiniDMS.php on line 53"

The config including these two variables get outputed, so the scripts loads the correct config but however does not recognize the variables

**Comment by cutzenfriend** [comment]
I have the absolut same issue! Which PHP Version are you using? I use 7.0 maybe thats the issue?

**Comment by Willi08** [comment]
Same Error, change in config.php at the beginning 
` <?  `
to
` <?php `

this solves the problem...

**Comment by stweiss** [comment]
Thanks @Willi08! I'll update that ...
