### ISSUE TITLE
Prevent "Re-OCRing"

### ISSUE THREAD

**Issue by Guacam-Ole** [stweiss/FileBasedMiniDMS#9]
I currently have the problem that once "OCRed" documents are rechecked. So I end up having files like 
"OCR_OCR_OCR_OCR_OCR_Rechnung34.pdf"

I do not have a specific Prefix for non-checked PDFs (they can have about any filename), so "MatchWithoutOcr" is "*" instead of "Scan*". Is there any way to let the tool ignore all files that have the "OCR_"-prefix?

**Comment by stweiss** [comment]
It was not intended to have matchWithoutOCR to be empty.
I prepared a fix, but could not test it. Can you go for it and give feedback?

You just need to replace FileBasedMiniDMS.php from here:
[FileBasedMiniDMS.php](https://github.com/stweiss/FileBasedMiniDMS/raw/stweiss-patch-1/FileBasedMiniDMS.php)

**Comment by Guacam-Ole** [comment]
That was quick :)
I changed the code a little bit (**not** *to be merged, only to test if everything works*) to the following:
```
 if ($OCRPrefix &&
                fnmatch($OCRPrefix . '*', $scanpath_parts['filename'], FNM_CASEFOLD)) {
                	 trace(LOG_INFO, "OCR ignored for \"".$scanpath_parts['filename']."\" \n");
                continue;
                }
```
And the output looks fine:
> [...]
> 2018-11-07 21:31:29 OCR ignored for "OCR_OCR_OCR_OCR_OCR_Contract sheet_002192" 
> 2018-11-07 21:31:29 OCR ignored for "OCR_OCR_OCR_OCR_OCR_Contract sheet_002193" 
> 2018-11-07 21:31:29 OCR ignored for "OCR_OCR_OCR_OCR_OCR_Contract sheet_002194" 
> 2018-11-07 21:31:43 OCR'd "/volume1/gdocs/scans/this should be ocr'ed.pdf" with status 0

Thanks!
